#!/usr/bin/env node
/**
 * Write the canister ids the frontend needs into `.env`.
 *
 * icp-cli has no `dfx generate` / `output_env_file` equivalent. What it does
 * give you is environment variables during **sync** steps:
 *
 *   ICP_CLI_CID              the canister being synced
 *   ICP_CLI_CID_<NAME>       every canister in the environment, name uppercased
 *                            with non-alphanumerics replaced by underscores
 *   ICP_CLI_ENVIRONMENT      e.g. "local"
 *   ICP_CLI_NETWORK          e.g. "local" or "ic"
 *
 * Vite reads this file (see frontend/vite.config.ts `envDir` + `envPrefix`).
 *
 * Run standalone outside a sync step and it falls back to `icp canister
 * status --id-only`, so `npm run dev` works without a full deploy.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { frontendTarget } from "./frontend-target.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = resolve(ROOT, ".env");

// A command-line target is an operator decision and must not be redirected by
// stale sync variables. With no argument (the icp.yaml sync case), the CLI's
// scoped values remain authoritative.
const target = frontendTarget(process.argv.slice(2));
const { environment, network } = target;
const isLocal = network !== "ic";

/** Gateway port for the managed local network; keep in sync with icp.yaml. */
const LOCAL_PORT = 8943;

function fromCli(name) {
  try {
    return execFileSync(
      "icp",
      ["canister", "status", name, "--id-only", "--environment", environment],
      { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
  } catch {
    return "";
  }
}

function canisterId(name) {
  const key = `ICP_CLI_CID_${name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}`;
  // An ambient canister id belongs to the ambient sync target. Never combine
  // it with a different environment explicitly requested on the command line.
  return (target.inheritSyncCanisterIds ? process.env[key] : "") || fromCli(name);
}

const hackathon = canisterId("hackathon");
if (!hackathon) {
  console.error("could not resolve the hackathon canister id - run `icp deploy` first");
  process.exit(1);
}

// Only deployed locally; on ic the frontend uses the real https://id.ai.
const internetIdentity = isLocal ? canisterId("internet_identity") : "";

// Internet Identity's production origin is https://id.ai, NOT the older
// identity.ic0.app. Locally it is our own pinned II canister.
const identityProvider = isLocal
  ? `http://${internetIdentity}.localhost:${LOCAL_PORT}`
  : "https://id.ai";

const lines = [
  "# Generated by scripts/write-env.mjs. Do not edit; do not commit.",
  `VITE_ICP_ENVIRONMENT=${environment}`,
  `VITE_ICP_NETWORK=${network}`,
  `VITE_CANISTER_ID_HACKATHON=${hackathon}`,
  `VITE_IDENTITY_PROVIDER=${identityProvider}`,
  "",
];

writeFileSync(ENV_PATH, lines.join("\n"));

console.log(`.env written for environment "${environment}"`);
console.log(`  hackathon          ${hackathon}`);
console.log(`  identity provider  ${identityProvider}`);
if (isLocal) {
  if (!internetIdentity) console.log("  warning: internet_identity is not deployed");
  console.log(`  app                http://${hackathon}.localhost:${LOCAL_PORT}/`);
}
